FROM ubuntu

RUN apt-get update -y

RUN apt-get upgrade -y

# TOOLS

RUN apt-get install apt-utils -y

RUN apt-get install git -y

RUN apt-get install vim -y


# COMPILERS

RUN apt-get install g++ -y

RUN apt-get install gcc -y

CMD /bin/bash

